### ISSUE TITLE
Latest changes don't work in IE8

### ISSUE THREAD

**Issue by coliff** [namiltd/bootstrap-ie#2]
Hi there. I merged these changes in to https://github.com/coliff/bootstrap-ie8/ - however the JavaScript doesn't appear to work in IE8. Can you please take a look? 

http://coliff.github.io/bootstrap-ie8/test.htm
http://namiltd.github.io/bootstrap-ie8/test.htm
^ dropdowns or modals are not working

**Comment by namiltd** [comment]
Fixed: https://github.com/namiltd/bootstrap-ie8/commit/0717156333c6f7ba9751dcebbbf79e034eadca28 and https://github.com/namiltd/bootstrap-ie8/commit/7f74da4582f48c2c4bea2e36d190c527f670520c
